# Generated by Django 4.0 on 2021-12-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guideversion',
            unique_together={('guide', 'version')},
        ),
    ]
