# Generated by Django 4.0 on 2021-12-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
