# Generated by Django 4.0 on 2021-12-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0002_alter_guide_description_alter_guide_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
