# Generated by Django 4.0 on 2021-12-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0003_remove_guideitem_version_guideversion_guide_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideversion',
            old_name='guide_item',
            new_name='guide_items',
        ),
    ]
