# Generated by Django 4.0 on 2021-12-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0003_alter_guide_description_alter_guide_short_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guide',
            unique_together={('name', 'version')},
        ),
    ]
