# Generated by Django 4.0 on 2021-12-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0004_alter_guide_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
