# Generated by Django 4.0 on 2021-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0004_rename_guide_item_guideversion_guide_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideversion',
            name='version',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
