# Generated by Django 4.0 on 2021-12-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0005_alter_guide_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['name', 'start_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='guideitem',
            options={'ordering': ['code', 'guide', 'id']},
        ),
    ]
