# Generated by Django 4.0 on 2021-12-17 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0005_alter_guideversion_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideversion',
            name='version',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
