# Generated by Django 4.0 on 2021-12-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0007_alter_guideversion_version_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guideitem',
            constraint=models.CheckConstraint(check=models.Q(('code', ''), _negated=True), name='non_empty_code'),
        ),
    ]
