# Generated by Django 4.0 on 2021-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0008_guideitem_non_empty_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guideitem',
            constraint=models.CheckConstraint(check=models.Q(('value', ''), _negated=True), name='non_empty_value'),
        ),
    ]
